MODEL:
    name: resnet34
    n_classes: 2
    pretrained: True
    path:  models/object-CXR/R_34_1x_DA.pt
    last_layer: [layer2, layer3, layer4, layer4]
    last_block: [0, 0, 0, 2]
    phase1: conv3x3
DATASET:
    name: object-CXR
    size: 600
    path: images/object-CXR_test/images/
    target_class: null
RESULTS:
    dir: results/visualization_on_image/object-CXR_test/combined_conv3x3/
    alpha: 0.4
    DRAW_GT_BBOX:
        state: True
        gt_src: images/object-CXR_test/test.csv
    POINTING_GAME:
        state: True
        tolerance: 25
        gt_src: images/object-CXR_test/dev.csv
    save_preds_to: results/visualization_on_image/object-CXR_test/combined_conv3x3/preds.csv
